---
title: "Weather Station Data"
author: "Caroline Shepherd"
date: "2024-04-08"
output:
  html_document:
    theme: cerulean
    code_folding: hide
    highlight: monochrome
    toc: yes
    toc_depth: 5
    toc_float: yes
    collapsed: yes
    smooth_scroll: yes
    number_sections: no
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#load packages

library(tidyverse)
library(here)
library(lubridate)

```


```{r}

#read in the data
#immediately changing wacky ass column names
annie_oakley <- read_csv(here("Annie_Oakly.csv")) %>% 
  rename(id = "#",
         date_time = "Date Time, GMT-07:00",
         temp_f = "Temp, °F (LGR S/N: 21901550, SEN S/N: 21895909, LBL: Temperature)",
         rh_percent = "RH, % (LGR S/N: 21901550, SEN S/N: 21895909, LBL: RH)",
         solar_rad_wm2 = "Solar Radiation, W/m² (LGR S/N: 21901550, SEN S/N: 21903642, LBL: Solar Radiation)",
         rain_in = "Rain, in (LGR S/N: 21901550, SEN S/N: 21907472, LBL: Rain)",
         soil_moist_m3m3 = "Water Content, m³/m³ (LGR S/N: 21901550, SEN S/N: 21907600, LBL: Water Content)",
         wind_sp_mph = "Wind Speed, mph (LGR S/N: 21901550, SEN S/N: 21907851, LBL: Wind Speed)",
         gust_sp_mph = "Gust Speed, mph (LGR S/N: 21901550, SEN S/N: 21907851, LBL: Gust Speed)",
         wind_direct = "Wind Direction, ø (LGR S/N: 21901550, SEN S/N: 21907851, LBL: Wind Direction)") %>%
  mutate("date_time2" = (mdy_hm("03/27/2024 9:03"))) %>% 
  separate(col = date_time2,
           into = c("date", "time"),
           sep = " ")

annie_oakley$date <- ymd(annie_oakley$date)

annie_oakley$time <- hm(annie_oakley$time)

class(annie_oakley$date)
class(annie_oakley$time)

```




