---
title: "Oak Fuel Break - Initial Analysis"
author: "Caroline Shepherd"
date: "2024-02-21"
output:
  html_document:
    theme: cerulean
    code_folding: hide
    highlight: monochrome
    toc: yes
    toc_depth: 5
    toc_float: yes
    collapsed: yes
    smooth_scroll: yes
    number_sections: no
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Santa Barbara Botanic Garden's Oak Fuel Break - Data Analysis

## This code aims to visualize and summarize mortality data from SBBG's Oak Fuel Break experiment. It has been made publically accessible, but these results have not been published, so please understand that we are still collecting data and making changes to this code.

```{r}

#load packages

library(cowplot)
library(tidyverse)
library(janitor)
library(here)

```

```{r}

# read in the data and clean it up. Clean names and change the As and Ds to 1s and 0s for easier calculations
oak_data <- read.csv(here("data", "mortality_biomass", "oak_mortality_biomass_data_jul2024.csv")) %>% 
  clean_names() %>%
  mutate(mortality_status = recode(mortality_status_a_or_d, A = '1', D = '0')) %>% 
  group_by(plot)

oak_data$mortality_status1 = as.numeric(oak_data$mortality_status)

# making sure R knows dates are dates (lbd is short for lubridate)
oak_data$date_lbd <- parse_date_time(oak_data$date, "ymd")

# creating datasets for replanted trees and original plantings
replanted_oaks <- oak_data %>% filter(replanted == "1")

replanted_oaks_total <- oak_data %>% filter(replanted == "1") %>% 
  summarise(sum_replant_alive = sum(replanted))

og_oaks <- oak_data %>% filter(replanted == "0")

og_oaks_total <- oak_data %>% filter(replanted == "0") %>% 
  summarise(sum_og_alive = sum(replanted))

```

```{r}

#exploring the data

mort_plot <- oak_data %>% 
  filter(replanted == "0") %>% 
  group_by(plot) %>% 
  summarise(mort_sum = sum(mortality_status1, na.rm = TRUE))

ggplot(data = mort_plot, aes(y = mort_sum, x = plot)) +
  geom_col() +
  labs(x = "Plot ID",
       y = "Total Trees Alive",
       title = "Original Oak Trees: Total number still alive (June 2024)") +
  theme_bw()


mort_age_plot <- oak_data %>% 
  filter(replanted == "0") %>% 
  group_by(plot, tree_age) %>% 
  summarise(mort_sum = sum(mortality_status1, na.rm = TRUE))
  

ggplot(data = mort_age_plot, aes(y = mort_sum, x = tree_age, group_by(plot))) +
  geom_col() +
  labs(x = "Plot ID",
       y = "Total Trees Alive",
       title = "Original Oak Trees: Total number still alive (June 2024)") +
  theme_bw()

```


```{r}

# Analysis by plot

# Plot 1

p1_mort_plot <- oak_data %>% 
  filter(plot == "1",
         replanted == "0") %>% 
  group_by(tree_age) %>% 
  summarise(mort_sum = mortality_status1, na.rm = TRUE)

ggplot(data = p1_mort_plot, aes(x = tree_age, y = mort_sum)) +
  geom_col() +
  theme_bw() +
  labs(x = "Age of Tree",
       y = "Number of Trees Alive",
       title = "Number of living trees in plot 1 grouped by age of tree when planted")

# Plot 2

p2_mort_plot <- oak_data %>% 
  filter(plot == "2",
         replanted == "0") %>% 
  group_by(tree_age) %>% 
  summarise(mort_sum = mortality_status1, na.rm = TRUE)

ggplot(data = p2_mort_plot, aes(x = tree_age, y = mort_sum)) +
  geom_col() +
  theme_bw() +
  labs(x = "Age of Tree",
       y = "Number of Trees Alive",
       title = "Number of living trees in plot 2 grouped by age of tree when planted")

# Plot 3

p3_mort_plot <- oak_data %>% 
  filter(plot == "3",
         replanted == "0") %>% 
  group_by(tree_age) %>% 
  summarise(mort_sum = mortality_status1, na.rm = TRUE)

ggplot(data = p3_mort_plot, aes(x = tree_age, y = mort_sum)) +
  geom_col() +
  theme_bw() +
  labs(x = "Age of Tree",
       y = "Number of Trees Alive",
       title = "Number of living trees in plot 3 grouped by age of tree when planted")

# need to combine these somehow

```

