---
title: "Weather Station Data"
author: "Caroline Shepherd"
date: "2024-04-08"
output:
  html_document:
    theme: cerulean
    code_folding: hide
    highlight: monochrome
    toc: yes
    toc_depth: 5
    toc_float: yes
    collapsed: yes
    smooth_scroll: yes
    number_sections: no
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#load packages

library(tidyverse)
library(dplyr)
library(here)

```


```{r}

# Read in the data
# Immediately changing wacky column names
annie_oakly <- read_csv(here("data", "Annie_Oakly.csv")) %>% 
  rename(id = "#",
         date_time = "Date Time, GMT-07:00",
         temp_f = "Temp, °F (LGR S/N: 21901550, SEN S/N: 21895909, LBL: Temperature)",
         rh_percent = "RH, % (LGR S/N: 21901550, SEN S/N: 21895909, LBL: RH)",
         solar_rad_wm2 = "Solar Radiation, W/m² (LGR S/N: 21901550, SEN S/N: 21903642, LBL: Solar Radiation)",
         prec_in = "Rain, in (LGR S/N: 21901550, SEN S/N: 21907472, LBL: Rain)",
         soil_m3m3 = "Water Content, m³/m³ (LGR S/N: 21901550, SEN S/N: 21907600, LBL: Water Content)",
         wind_sp_mph = "Wind Speed, mph (LGR S/N: 21901550, SEN S/N: 21907851, LBL: Wind Speed)",
         gust_sp_mph = "Gust Speed, mph (LGR S/N: 21901550, SEN S/N: 21907851, LBL: Gust Speed)",
         wind_direct = "Wind Direction, ø (LGR S/N: 21901550, SEN S/N: 21907851, LBL: Wind Direction)") 

# using lubridate to change date_time to date class
annie_oakly$date_time_local <- parse_date_time(annie_oakly$date_time, "mdy HM")


# Reading in second weather station data
oakie_dokie <- read_csv(here("data", "Oakie_Dokie_2.csv")) %>%
  rename(id = "#",
         date_time = "Date Time, GMT-08:00",
         temp_f = "Temp, °F (LGR S/N: 21901549, SEN S/N: 21895908, LBL: Temp)",
         rh_percent = "RH, % (LGR S/N: 21901549, SEN S/N: 21895908, LBL: RH)",
         solar_rad_wm2 = "Solar Radiation, W/m² (LGR S/N: 21901549, SEN S/N: 21903641, LBL: Solar Radiation)",
         prec_in = "Rain, in (LGR S/N: 21901549, SEN S/N: 21907471, LBL: Rain)",
         soil_m3m3 = "Water Content, m³/m³ (LGR S/N: 21901549, SEN S/N: 21900338, LBL: Water Content)",
         wind_sp_mph = "Wind Speed, mph (LGR S/N: 21901549, SEN S/N: 21907852, LBL: Wind Speed)",
         gust_sp_mph = "Gust Speed, mph (LGR S/N: 21901549, SEN S/N: 21907852, LBL: Gust Speed)",
         wind_direct = "Wind Direction, ø (LGR S/N: 21901549, SEN S/N: 21907852, LBL: Wind Direction)")

oakie_dokie$date_time_local <- parse_date_time(oakie_dokie$date_time, "mdy HM")


# Initial plots for Annie Oakly

ggplot(annie_oakly, aes(x = date_time_local, y = temp_f)) +
  geom_point() +
  geom_line() +
  scale_x_datetime(breaks = "1 day") +
  theme_bw()

ggplot(annie_oakly, aes(x=date_time_local, y=prec_in))+
  geom_col()+
  scale_x_datetime(breaks="1 day")+
  theme_bw()

ggplot(annie_oakly, aes(x = date_time_local, y = soil_m3m3)) +
  geom_point() +
  geom_line() +
  scale_x_datetime(breaks = "1 day") +
  theme_bw()

# Initial plots for Oakie Dokie

ggplot(oakie_dokie, aes(x = date_time_local, y = temp_f)) +
  geom_point() +
  geom_line() +
  scale_x_datetime(breaks = "1 day") +
  theme_bw()

ggplot(oakie_dokie, aes(x=date_time_local, y=prec_in))+
  geom_col()+
  scale_x_datetime(breaks="1 day")+
  theme_bw()

ggplot(oakie_dokie, aes(x = date_time_local, y = soil_m3m3)) +
  geom_point() +
  geom_line() +
  scale_x_datetime(breaks = "1 day") +
  theme_bw()


```




